documentation:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.md"
          - "docs/**"

tests:
  - changed-files:
      - any-glob-to-any-file:
          - "tests/**"

maintenance:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/**"

