python:
  - changed-files:
      - any-glob-to-any-file:
          - "custom_components/**"

frontend:
  - changed-files:
      - any-glob-to-any-file:
          - "custom_components/city_visitor_parking/frontend/**"

testing:
  - head-branch: ["testing"]
