name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
commitish: "main"
change-template: "- $TITLE (#$NUMBER)"
no-changes-template: "- No changes"
sort-direction: ascending
categories:
  - title: "⚠️ Breaking Changes"
    labels:
      - "breaking-change"
  - title: "Added"
    labels:
      - "new-feature"
  - title: "Fixed"
    labels:
      - "bugfix"
  - title: "Changed"
    labels:
      - "maintenance"
      - "enhancement"
      - "refactor"
      - "performance"
      - "ci"
      - "dependencies"
  - title: "Tests"
    labels:
      - "tests"
  - title: "Docs"
    labels:
      - "documentation"
version-resolver:
  major:
    labels:
      - "major"
      - "breaking-change"
  minor:
    labels:
      - "minor"
      - "new-feature"
  patch:
    labels:
      - "bugfix"
      - "ci"
      - "dependencies"
      - "documentation"
      - "enhancement"
      - "maintenance"
      - "performance"
      - "refactor"
      - "tests"
  default: patch
autolabeler:
  - label: "documentation"
    files:
      - "**/*.md"
      - "docs/**"
  - label: "tests"
    files:
      - "tests/**"
  - label: "maintenance"
    files:
      - ".github/**"
template: |
  $CHANGES
