name-template: "$NEXT_PATCH_VERSION"
tag-template: "$NEXT_PATCH_VERSION"
commitish: "main"
change-template: "- $TITLE (#$NUMBER)"
no-changes-template: "- No changes"
categories:
  - title: "Added"
    labels:
      - "feature"
      - "enhancement"
  - title: "Fixed"
    labels:
      - "bug"
      - "fix"
  - title: "Changed"
    labels:
      - "chore"
      - "maintenance"
  - title: "Tests"
    labels:
      - "tests"
  - title: "Docs"
    labels:
      - "documentation"
autolabeler:
  - label: "documentation"
    files:
      - "**/*.md"
      - "docs/**"
  - label: "tests"
    files:
      - "tests/**"
  - label: "maintenance"
    files:
      - ".github/**"
template: |
  $CHANGES
