name: "Hassfest"
description: "Run hassfest checks"
runs:
  using: "composite"
  steps:
    - shell: bash
      run: echo "::add-matcher::${{ github.action_path }}/problem-matcher.json"
    - shell: bash
      run: |
        docker run --rm -v ${{ github.workspace }}://github/workspace ghcr.io/home-assistant/hassfest
